"""Add cmo_chat_messages table

Revision ID: 15381213704c
Revises: 7d4b3424e102
Create Date: 2025-11-30 00:27:17.851310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15381213704c'
down_revision: Union[str, Sequence[str], None] = '7d4b3424e102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmo_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmo_chat_messages_created_at'), 'cmo_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_cmo_chat_messages_id'), 'cmo_chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmo_chat_messages_id'), table_name='cmo_chat_messages')
    op.drop_index(op.f('ix_cmo_chat_messages_created_at'), table_name='cmo_chat_messages')
    op.drop_table('cmo_chat_messages')
    # ### end Alembic commands ###
